### ISSUE TITLE
Add fsPickler to binary serializer test

### ISSUE THREAD

**Issue by theburningmonk** [theburningmonk/SimpleSpeedTester#6]

**Comment by davidgrenier** [comment]
Hey mate, if you find the time to merge the other pull request, I actually have another commit on my fork that I could submit to you for FsPickler.

Performance seems good but not on par with the other fast ones for SimpleObjects

**Comment by theburningmonk** [comment]
Merged.

**Comment by davidgrenier** [comment]
Saw that...

Thinking there must be a way to include a third line in the graph for the
payload size... I believe this could be worth it.

Let me know if you want me to look into it.

**Comment by theburningmonk** [comment]
Sure, if you don't mind! :-)
